{"level":"error","message":"Error conectando a la base de datos: Error: Access denied for user 'root'@'localhost' (using password: YES)\n    at Packet.asError (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n    at ClientHandshake.execute (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n    at Connection.handlePacket (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n    at PacketParser.onPacket (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n    at PacketParser.executeStart (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n    at Socket.<anonymous> (C:\\Users\\PAULA_MORENO\\Desktop\\AppBld\\AppInspectorBuild\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)","timestamp":"2025-01-28T19:21:26.248Z"}
{"level":"error","message":"Error conectando a la base de datos: AggregateError [ECONNREFUSED]: \n    at internalConnectMultiple (node:net:1116:18)\n    at afterConnectMultiple (node:net:1683:7) - Verifica que la contraseña y el servidor MySQL estén funcionando.","timestamp":"2025-02-08T17:05:46.935Z"}
